/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import pg.Comerciante;
import pg.Consumidor;
import pg.EFactur;
import pg.Utilizador;

/**
 *
 * @author Nuno
 */
public class ADListaUtilizadores extends javax.swing.JFrame {

    EFactur sistema;
    public ADListaUtilizadores(EFactur sistema) {
        this.sistema = sistema;
        initComponents();
        
        getContentPane().setBackground(Color.WHITE);
        jTutilizadores.setForeground(Color.WHITE);
        jTutilizadores.setBackground(Color.GRAY);
        jCcae.setVisible(false);
        pack();
        listaTodos();
        
    }
    
    private void listaTodos(){
       
        ArrayList<Comerciante> listaComerciante = sistema.listaComerciantes();
        ArrayList<Consumidor> listaConsumidor = sistema.listaConsumidores();
        DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[] {"NIF", "Nome", "Morada", "Telefone", "Telemovel", "Cartao Cidadao", "Password", "CAE"});
            
            for (Comerciante p : listaComerciante){
                    model.addRow(new String[] {p.getNif(), p.getNome(), p.getMorada(), p.getTelefone(), p.getTelemovel(), p.getCc(), p.getPassword(),p.getCAE()});
            }
            
            for (Consumidor p : listaConsumidor){
                    model.addRow(new String[] {p.getNif(), p.getNome(), p.getMorada(), p.getTelefone(), p.getTelemovel(), p.getCc(), p.getPassword()});
            }
            
            jTutilizadores.setModel(model);
            pack();
        
    }
    
    
    public void listaCom(String parametro){
        ArrayList<Comerciante> listaComerciante = new ArrayList<>();
        
        
        switch (parametro) {
            case "Cabeleireiro":
                listaComerciante = sistema.comerciantesPorCAE(parametro);
                break;              
            case "Mecanico":
               listaComerciante = sistema.comerciantesPorCAE(parametro);
                break;
            case "Restauração":
               listaComerciante = sistema.comerciantesPorCAE(parametro);
                break;
            case "Todos":
                listaComerciante = sistema.listaComerciantes();
                break;
            
        }
        
        
        DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[] {"NIF", "Nome", "Morada", "Telefone", "Telemovel", "Cartao Cidadao", "Password", "CAE"});
            
            for (Comerciante p : listaComerciante){
                    model.addRow(new String[] {p.getNif(), p.getNome(), p.getMorada(), p.getTelefone(), p.getTelemovel(), p.getCc(), p.getPassword(),p.getCAE()});
            }
        jTutilizadores.setModel(model);
            pack();
            
        
    }
    
    public void listaCon(){
        ArrayList<Consumidor> listaConsumidor = sistema.listaConsumidores();
        DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[] {"NIF", "Nome", "Morada", "Telefone", "Telemovel", "Cartao Cidadao", "Password"});
        for (Consumidor p : listaConsumidor){
                    model.addRow(new String[] {p.getNif(), p.getNome(), p.getMorada(), p.getTelefone(), p.getTelemovel(), p.getCc(), p.getPassword()});
            }
            
            jTutilizadores.setModel(model);
            pack();    
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTutilizadores = new javax.swing.JTable();
        jCselector = new javax.swing.JComboBox();
        jCcae = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 255));

        jTutilizadores.setAutoCreateRowSorter(true);
        jTutilizadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIF", "NOME", "PASSWORD", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTutilizadores);

        jCselector.setBackground(new java.awt.Color(204, 204, 255));
        jCselector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Comerciantes", "Consumidores" }));
        jCselector.setSelectedIndex(-1);
        jCselector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCselectorActionPerformed(evt);
            }
        });

        jCcae.setBackground(new java.awt.Color(204, 204, 255));
        jCcae.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cabeleireiro", "Mecanico", "Restauração" }));
        jCcae.setSelectedIndex(-1);
        jCcae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcaeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jCselector, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCcae, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCselector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCcae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCselectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCselectorActionPerformed
    
         switch (jCselector.getSelectedItem().toString()) {
            case "Todos":
                jCcae.setVisible(false);
                pack();
                listaTodos();
                break;              
            case "Consumidores":
               jCcae.setVisible(false);
               pack();
               listaCon();
               break;
            case "Comerciantes":
               jCcae.setVisible(true);
               pack();
               listaCom("Todos");
               break;
            
            
        }
    }//GEN-LAST:event_jCselectorActionPerformed

    private void jCcaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcaeActionPerformed
        switch (jCcae.getSelectedItem().toString()) {
            case "Cabeleireiro":
                listaCom("Cabeleireiro");
                break;              
            case "Mecanico":
               listaCom("Mecanico");
                break;
            case "Restauração":
               listaCom("Restauração");
                break;
            
            
        }
     
        
      
    }//GEN-LAST:event_jCcaeActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCcae;
    private javax.swing.JComboBox jCselector;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTutilizadores;
    // End of variables declaration//GEN-END:variables
}
