/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import javax.swing.JOptionPane;
import pg.*;

/**
 *
 * @author Nuno
 */
public class ADnovoUtilizador extends javax.swing.JFrame {
    private EFactur sistema;
    String utilizador;
    String cae;
    public ADnovoUtilizador(String utilizador, EFactur sistema) {
        this.sistema = sistema;
        this.utilizador = utilizador;
        
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        
        this.utilizador = utilizador;
        jCcae.setVisible(false);
        jLcae.setVisible(false);
        jBfaturas.setVisible(false);
        jBeditar.setVisible(false);
        jBremover.setVisible(false);
        pack();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        switch (utilizador) {
            case "Comerciante":
                jCcae.setVisible(true);
                jLcae.setVisible(true);
                pack();
                break;
            case "Consumidor":
                jCcae.setVisible(false);
                jLcae.setVisible(false);
                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                pack();
                break;
            case "Consulta":
                desactiva();
                jBadicionar.setText("Procurar");
                pack();
                break;
            
                
        }
    }
    
   public ADnovoUtilizador(Utilizador utilizador, EFactur sistema) {
    
    initComponents();   
    if(sistema.devolveComerciante(utilizador.getNif())!= null){     
        jTcc.setEnabled(false);
        jTmorada.setEnabled(true);
        jTnome.setEnabled(false);
        jTpassword.setEnabled(true);
        jTtelefone.setEnabled(true);
        jTtelemovel.setEnabled(true);
        jTnif.setEnabled(false);
        jCcae.setVisible(false);
        jLcae.setVisible(false);
        jTnif.setText(utilizador.getNif());
        jTcc.setText(utilizador.getCc());
        jTmorada.setText(utilizador.getMorada());
        jTnome.setText(utilizador.getNome());
        jTpassword.setText(utilizador.getPassword());
        jTtelefone.setText(utilizador.getTelefone());
        jTtelemovel.setText(utilizador.getTelemovel());
        jBadicionar.setText("Gravar");
    } else { 
        jTcc.setEnabled(false);
        jTmorada.setEnabled(true);
        jTnome.setEnabled(false);
        jTpassword.setEnabled(true);
        jTtelefone.setEnabled(true);
        jTtelemovel.setEnabled(true);
        jTnif.setEnabled(false);
        jCcae.setVisible(false);
        jLcae.setVisible(false);  
       
    }
    
    
       


   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTnif = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTpassword = new javax.swing.JTextField();
        jLcae = new javax.swing.JLabel();
        jCcae = new javax.swing.JComboBox();
        jBadicionar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTmorada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTtelefone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTtelemovel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTcc = new javax.swing.JTextField();
        jBeditar = new javax.swing.JButton();
        jBfaturas = new javax.swing.JButton();
        jBremover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(451, 425));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Nome");

        jTnome.setBackground(new java.awt.Color(204, 204, 255));
        jTnome.setDisabledTextColor(java.awt.Color.blue);

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("NIF");

        jTnif.setBackground(new java.awt.Color(204, 204, 255));
        jTnif.setDisabledTextColor(java.awt.Color.blue);
        jTnif.setMinimumSize(new java.awt.Dimension(160, 20));
        jTnif.setPreferredSize(new java.awt.Dimension(160, 20));
        jTnif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnifActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Password");

        jTpassword.setBackground(new java.awt.Color(204, 204, 255));
        jTpassword.setDisabledTextColor(java.awt.Color.blue);

        jLcae.setBackground(new java.awt.Color(204, 204, 255));
        jLcae.setText("CAE");

        jCcae.setBackground(new java.awt.Color(204, 204, 255));
        jCcae.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cabeleireiro", "Mecanico", "Restauração" }));
        jCcae.setSelectedIndex(-1);
        jCcae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcaeActionPerformed(evt);
            }
        });

        jBadicionar.setBackground(new java.awt.Color(204, 204, 255));
        jBadicionar.setText("Adicionar");
        jBadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBadicionarActionPerformed(evt);
            }
        });

        jBcancelar.setBackground(new java.awt.Color(204, 204, 255));
        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Morada");

        jTmorada.setBackground(new java.awt.Color(204, 204, 255));
        jTmorada.setDisabledTextColor(java.awt.Color.blue);

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Telefone");

        jTtelefone.setBackground(new java.awt.Color(204, 204, 255));
        jTtelefone.setDisabledTextColor(java.awt.Color.blue);

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Telemovel");

        jTtelemovel.setBackground(new java.awt.Color(204, 204, 255));
        jTtelemovel.setDisabledTextColor(java.awt.Color.blue);

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setText("Cartao de Cidadao");

        jTcc.setBackground(new java.awt.Color(204, 204, 255));
        jTcc.setDisabledTextColor(java.awt.Color.blue);

        jBeditar.setBackground(new java.awt.Color(204, 204, 255));
        jBeditar.setText("Editar");
        jBeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditarActionPerformed(evt);
            }
        });

        jBfaturas.setBackground(new java.awt.Color(204, 204, 255));
        jBfaturas.setText("Faturas");
        jBfaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfaturasActionPerformed(evt);
            }
        });

        jBremover.setBackground(new java.awt.Color(204, 204, 255));
        jBremover.setText("Remover");
        jBremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBremoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                        .addGap(69, 69, 69))
                    .addComponent(jTmorada)
                    .addComponent(jTnome)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCcae, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLcae, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTnif, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTpassword, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBfaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTtelefone)
                                .addComponent(jLabel6)
                                .addComponent(jTtelemovel)
                                .addComponent(jLabel7)
                                .addComponent(jTcc, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBcancelar)
                            .addComponent(jBadicionar)
                            .addComponent(jBremover))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTnif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTmorada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTtelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLcae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCcae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBremover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBadicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBcancelar)
                            .addComponent(jBfaturas)
                            .addComponent(jBeditar))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBadicionarActionPerformed
        if(jBadicionar.getText().toString().equals("Adicionar")){
        if("".equals(jTnome.getText())){
            JOptionPane.showMessageDialog(this, "Insira o nome","Novo Utilizador", JOptionPane.WARNING_MESSAGE);
        } else { if ("".equals(jTnif.getText())){
            JOptionPane.showMessageDialog(this, "Insira o nif","Novo Utilizador", JOptionPane.WARNING_MESSAGE);
        } else { if ("".equals(jTpassword.getText())){
            JOptionPane.showMessageDialog(this, "Insira a password","Novo Utilizador", JOptionPane.WARNING_MESSAGE);
        } else { if (jTnif.getText().length()!=9){
            JOptionPane.showMessageDialog(this, "Nif invalido","Novo Utilizador", JOptionPane.WARNING_MESSAGE);
        } else {
            if("Comerciante".equals(utilizador)){
                Comerciante cm = new Comerciante(jTnif.getText(), jTnome.getText(), jTmorada.getText(), jTtelefone.getText(), jTtelemovel.getText(), jTcc.getText(), jTpassword.getText(),cae );
                sistema.insereComerciante(cm);
                JOptionPane.showMessageDialog(this, "Novo Comerciante inserido com sucesso","Novo Utilizador", JOptionPane.WARNING_MESSAGE);
                dispose();
            } else{
                Consumidor cn = new Consumidor(jTnif.getText(), jTnome.getText(), jTmorada.getText(), jTtelefone.getText(), jTtelemovel.getText(), jTcc.getText(), jTpassword.getText());
                sistema.insereConsumidor(cn);
                JOptionPane.showMessageDialog(this, "Novo Consumidor inserido com sucesso","Novo Utilizador", JOptionPane.WARNING_MESSAGE);
                dispose();
            }
        }
        }
        }
        }
        
        } else if(jBadicionar.getText().toString().equals("Procurar")){
            if(sistema.devolveComerciante(jTnif.getText())!=null){
                Comerciante cm = sistema.devolveComerciante(jTnif.getText());
                jBfaturas.setVisible(true);
                jBeditar.setVisible(true);
                jBremover.setVisible(true);
                jBadicionar.setText("Gravar");
                pack();
                jTcc.setText(cm.getCc());
                jTmorada.setText(cm.getMorada());
                jTnome.setText(cm.getNome());
                jTpassword.setText(cm.getPassword());
                jTtelefone.setText(cm.getTelefone());
                jTtelemovel.setText(cm.getTelemovel());
                jCcae.setSelectedItem(cm.getCAE());
                pack();
                
            } else if(sistema.devolveConsumidor(jTnif.getText())!=null){
                Consumidor cn = sistema.devolveConsumidor(jTnif.getText());
                jBfaturas.setVisible(true);
                jBeditar.setVisible(true);
                jBremover.setVisible(true);
                jBadicionar.setText("Gravar");
                pack();
                jTcc.setText(cn.getCc());
                jTmorada.setText(cn.getMorada());
                jTnome.setText(cn.getNome());
                jTpassword.setText(cn.getPassword());
                jTtelefone.setText(cn.getTelefone());
                jTtelemovel.setText(cn.getTelemovel());
                pack();
                
                
            } else {
                JOptionPane.showMessageDialog(this, "Insira um NIF valido","Edicao de utiliador", JOptionPane.WARNING_MESSAGE);
            } 
            
            
        } else if(jBadicionar.getText().toString().equals("Gravar")){
            if(sistema.devolveComerciante(jTnif.getText())!=null){
                Comerciante cm = sistema.devolveComerciante(jTnif.getText());
                cm.setCc(jTcc.getText());
                cm.setMorada(jTmorada.getText());
                cm.setNome(jTnome.getText());
                cm.setPassword(jTpassword.getText());
                cm.setTelefone(jTtelefone.getText());
                cm.setTelemovel(jTtelemovel.getText());
                cm.setCae(jCcae.getSelectedItem().toString());
                
                
                
            } else if(sistema.devolveConsumidor(jTnif.getText())!=null){
                Consumidor cn = sistema.devolveConsumidor(jTnif.getText());
                cn.setCc(jTcc.getText());
                cn.setMorada(jTmorada.getText());
                cn.setNome(jTnome.getText());
                cn.setPassword(jTpassword.getText());
                cn.setTelefone(jTtelefone.getText());
                cn.setTelemovel(jTtelemovel.getText());
                
                
            }
            pack();
            dispose();
        }
            
        
        
 
    }//GEN-LAST:event_jBadicionarActionPerformed

    private void jCcaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcaeActionPerformed
        if(jCcae.getSelectedItem()!=null){
            cae = jCcae.getSelectedItem().toString();
        } else {
            JOptionPane.showMessageDialog(this, "Insira o CAE","Novo Utilizador", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jCcaeActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
           dispose();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jTnifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnifActionPerformed
        
    }//GEN-LAST:event_jTnifActionPerformed

    private void jBeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditarActionPerformed
        activa();
    }//GEN-LAST:event_jBeditarActionPerformed

    private void jBfaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfaturasActionPerformed
        ADlistaFaturas lf = new ADlistaFaturas(sistema);
        lf.recebeNif(jTnif.getText());
        lf.setVisible(true);
    }//GEN-LAST:event_jBfaturasActionPerformed

    private void jBremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBremoverActionPerformed
        if(sistema.devolveComerciante(jTnif.getText())!= null){
            int resposta = JOptionPane.showConfirmDialog(this, "Tem a certeza que pretende remover este Comerciante", "Remove", JOptionPane.YES_NO_OPTION);
               if(resposta == JOptionPane.YES_NO_OPTION){
                   sistema.removeComerciante(sistema.devolveComerciante(jTnif.getText()));
        }
        }
        if(sistema.devolveConsumidor(jTnif.getText())!= null){
            int resposta = JOptionPane.showConfirmDialog(this, "Tem a certeza que pretende remover este Consumidor", "Remove", JOptionPane.YES_NO_OPTION);
               if(resposta == JOptionPane.YES_NO_OPTION){
                   sistema.removeConsumidor(sistema.devolveConsumidor(jTnif.getText()));
        }
        }
    }//GEN-LAST:event_jBremoverActionPerformed

    private void activa(){
        jTcc.setEnabled(true);
        jTmorada.setEnabled(true);
        jTnome.setEnabled(true);
        jTpassword.setEnabled(true);
        jTtelefone.setEnabled(true);
        jTtelemovel.setEnabled(true);
        jTnif.setEnabled(false);
        jCcae.setVisible(true);
        jLcae.setVisible(true);
        pack();
    }
    
    private void desactiva(){
        jTcc.setEnabled(false);
        jTmorada.setEnabled(false);
        jTnome.setEnabled(false);
        jTpassword.setEnabled(false);
        jTtelefone.setEnabled(false);
        jTtelemovel.setEnabled(false);
        jTnif.setEnabled(true);
        jCcae.setVisible(false);
        jLcae.setVisible(false);
        pack();
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBadicionar;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBeditar;
    private javax.swing.JButton jBfaturas;
    private javax.swing.JButton jBremover;
    private javax.swing.JComboBox jCcae;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLcae;
    private javax.swing.JTextField jTcc;
    private javax.swing.JTextField jTmorada;
    private javax.swing.JTextField jTnif;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTpassword;
    private javax.swing.JTextField jTtelefone;
    private javax.swing.JTextField jTtelemovel;
    // End of variables declaration//GEN-END:variables
}
