/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import java.awt.Color;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pg.EFactur;
import pg.Fatura;
import pg.FaturaLinha;
import pg.Utilizador;

/**
 *
 * @author Nuno
 */
public class InsereFatManual extends javax.swing.JFrame{

    private EFactur sistema;
    String nif;
    String tipoFatura;
    int taxa;
    double total;
    double iva;
    double baseTributavel;
    int contador=0;
    ArrayList<FaturaLinha> listaLinhas = new ArrayList<>();
    Utilizador ut;
    double totalLinhas;
    double ivaLinhas;
    double baseTribLinhas;
    DecimalFormat df= new DecimalFormat("#.##");
    
    public InsereFatManual(EFactur sistema, Utilizador ut) {
        this.sistema = sistema;
        this.ut = ut;
        
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        switch (ut.getClass().toString().substring(9)) {
            case "Comerciante":
                jTnifComerciante.setText(ut.getNif());
                jTnifComerciante.setEnabled(false);
                pack();
                break;
            case "Consumidor":
                jTnifConsumidor.setText(ut.getNif());
                jTnifConsumidor.setEnabled(false);
                jTnomeConsumidor.setText(ut.getNome());
                jTnomeConsumidor.setEnabled(false);
                pack();
                break;
        }
       
        
    }
    
    public InsereFatManual(EFactur sistema, Fatura f) {
        totalLinhas = 0;
        ivaLinhas = 0;
        baseTribLinhas = 0;
        initComponents();
        if(sistema.devolveComerciante(f.getIntrodPor())==null){
                jTnifConsumidor.setText(f.getNifReceptor().toString());
                jTnifConsumidor.setEnabled(false);
                jTnomeConsumidor.setText(f.getNome().toString());
                jTnomeConsumidor.setEnabled(false);
                jTnifComerciante.setText(f.getNifEmissor().toString());
                jTnumeroFatura.setText(f.getnFatura());
                ut = sistema.devolveComerciante(f.getIntrodPor());
                pack();
        } else{
                jTnifComerciante.setText(f.getNifEmissor().toString());
                jTnifComerciante.setEnabled(false);
                jTnomeConsumidor.setText(f.getNome().toString());
                jTnifConsumidor.setText(f.getNifReceptor().toString());
                jTnumeroFatura.setText(f.getnFatura().toString());
                ut = sistema.devolveConsumidor(f.getIntrodPor());
                pack();
        }
            
                
    }
    public void listaLinhas(){
            totalLinhas = 0;
            ivaLinhas = 0;
            baseTribLinhas = 0;
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[] {"Total", "Taxa", "Iva", "Base Tributavel"});
            
            for (FaturaLinha l : listaLinhas){
            model.addRow(new String[] {String.valueOf(l.getTotalLinha()), String.valueOf(l.getTaxa()), String.valueOf(l.getIva()), String.valueOf(l.getBaseTrib())});
            totalLinhas += l.getTotalLinha();
            ivaLinhas += l.getIva();
            baseTribLinhas += l.getBaseTrib();
            }
            jTlinhas.setModel(model);
            if(totalLinhas != 0){
                jLtotalLinhas.setText(String.valueOf(df.format(totalLinhas)));
                jLivaLinhas.setText(String.valueOf(df.format(ivaLinhas)));
                jLbaseTribLinhas.setText(String.valueOf(df.format(baseTribLinhas)));
                pack();
            }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTnifConsumidor = new javax.swing.JTextField();
        jTnomeConsumidor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTnifComerciante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCtipoFatura = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTnumeroFatura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jBadicionarLinha = new javax.swing.JButton();
        jBguardar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTlinhas = new javax.swing.JTable();
        jTtotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCtaxa = new javax.swing.JComboBox();
        jLtotalLinhas = new javax.swing.JLabel();
        jLbaseTribLinhas = new javax.swing.JLabel();
        jLivaLinhas = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Identificação da Fatura");

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("NIF Consumidor");

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Nome Consumidor");

        jTnifConsumidor.setBackground(new java.awt.Color(204, 204, 255));
        jTnifConsumidor.setDisabledTextColor(java.awt.Color.blue);
        jTnifConsumidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnifConsumidorActionPerformed(evt);
            }
        });

        jTnomeConsumidor.setBackground(new java.awt.Color(204, 204, 255));
        jTnomeConsumidor.setDisabledTextColor(java.awt.Color.blue);

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("NIF Comerciante");

        jTnifComerciante.setBackground(new java.awt.Color(204, 204, 255));
        jTnifComerciante.setDisabledTextColor(java.awt.Color.blue);
        jTnifComerciante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnifComercianteActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Tipo de Fatura");

        jCtipoFatura.setBackground(new java.awt.Color(204, 204, 255));
        jCtipoFatura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fatura", "Fatura Simplificada", "Nota de credito", "Nota de debito" }));
        jCtipoFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCtipoFaturaActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Número da Fatura");

        jTnumeroFatura.setBackground(new java.awt.Color(204, 204, 255));
        jTnumeroFatura.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTnumeroFatura.setText("Numero de Documento");
        jTnumeroFatura.setDisabledTextColor(java.awt.Color.blue);
        jTnumeroFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnumeroFaturaActionPerformed(evt);
            }
        });
        jTnumeroFatura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTnumeroFaturaFocusGained(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setText("Dados da Fatura");

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setText("Data de Emissão");

        jSeparator1.setBackground(new java.awt.Color(204, 204, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jBadicionarLinha.setBackground(new java.awt.Color(204, 204, 255));
        jBadicionarLinha.setText("Adicionar Linha");
        jBadicionarLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBadicionarLinhaActionPerformed(evt);
            }
        });

        jBguardar.setBackground(new java.awt.Color(204, 204, 255));
        jBguardar.setText("Guardar");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        jBcancelar.setBackground(new java.awt.Color(204, 204, 255));
        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 255));

        jTlinhas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TOTAL", "TAXA", "IVA", "BASE TRIBUTAVEL"
            }
        ));
        jScrollPane1.setViewportView(jTlinhas);

        jTtotal.setBackground(new java.awt.Color(204, 204, 255));
        jTtotal.setDisabledTextColor(java.awt.Color.blue);

        jLabel10.setBackground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("Total");

        jLabel11.setBackground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("Taxa");

        jCtaxa.setBackground(new java.awt.Color(204, 204, 255));
        jCtaxa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "23%", "22%", "16%", "13%", "12%", "9%", "6%", "5%", "4%", "Isento" }));
        jCtaxa.setSelectedIndex(-1);
        jCtaxa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCtaxaActionPerformed(evt);
            }
        });

        jLtotalLinhas.setBackground(new java.awt.Color(204, 204, 255));
        jLtotalLinhas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLtotalLinhas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtotalLinhas.setText("Total");

        jLbaseTribLinhas.setBackground(new java.awt.Color(204, 204, 255));
        jLbaseTribLinhas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLbaseTribLinhas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbaseTribLinhas.setText("Base Tributavel");

        jLivaLinhas.setBackground(new java.awt.Color(204, 204, 255));
        jLivaLinhas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLivaLinhas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLivaLinhas.setText("IVA");

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Remover ultima linha");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBguardar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBcancelar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTnifComerciante, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(jTnifConsumidor, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTnomeConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCtipoFatura, javax.swing.GroupLayout.Alignment.LEADING, 0, 199, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTnumeroFatura, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 52, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBadicionarLinha)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(25, 25, 25)
                                .addComponent(jTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jCtaxa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLtotalLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLivaLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLbaseTribLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTnifConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTnomeConsumidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTnifComerciante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCtipoFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTnumeroFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addGap(45, 45, 45)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBadicionarLinha)
                    .addComponent(jTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jCtaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLtotalLinhas)
                    .addComponent(jLbaseTribLinhas)
                    .addComponent(jLivaLinhas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBguardar)
                    .addComponent(jBcancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTnifConsumidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnifConsumidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnifConsumidorActionPerformed

    private void jTnifComercianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnifComercianteActionPerformed
            jTnifComerciante.setToolTipText(nif);
    }//GEN-LAST:event_jTnifComercianteActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
       
       Date d = new Date();

       SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
       
       System.out.println(jTnifComerciante.getText());
       System.out.println(jTnomeConsumidor.getText());
       System.out.println(jTnifConsumidor.getText());
       System.out.println(jCtipoFatura.getSelectedItem().toString());
       System.out.println(jTnumeroFatura.getText());
       System.out.println(formato.format(d));
       System.out.println(ut.getNif());
       System.out.println();
       Fatura f = new Fatura(jTnifComerciante.getText(), jTnomeConsumidor.getText(), jTnifConsumidor.getText(), jCtipoFatura.getSelectedItem().toString(), jTnumeroFatura.getText(), formato.format(d), ut.getNif(), (double)0);
       for (FaturaLinha l : listaLinhas){
           f.insereLinha(l);
       }
       f.actualizaTotalDeLinhas();
       if(ut.getClass().toString().substring(9).equals("Comerciante")){
       sistema.insereFaturaComerciante(f);
       } else { sistema.insereFaturaConsumidor(f);}
       dispose();
        
       
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jCtipoFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCtipoFaturaActionPerformed
    if(jCtipoFatura.getSelectedItem() != null){
        tipoFatura = jCtipoFatura.getSelectedItem().toString();
    }    
    }//GEN-LAST:event_jCtipoFaturaActionPerformed

    private void jBadicionarLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBadicionarLinhaActionPerformed
        if(jCtaxa.getSelectedItem()!= null && jTtotal.getText().length()!=0){
        Double total = Double.parseDouble(jTtotal.getText().toString());
        String taxaS = jCtaxa.getSelectedItem().toString();
        taxaS = taxaS.substring(0, taxaS.length() -1);
        Float taxa = Float.parseFloat(taxaS);
        FaturaLinha f = new FaturaLinha(total, taxa);
        listaLinhas.add(f);
        listaLinhas();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor insira o total e iva correspondente","Inserção de linhas", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jBadicionarLinhaActionPerformed

    private void jTnumeroFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnumeroFaturaActionPerformed
       
    }//GEN-LAST:event_jTnumeroFaturaActionPerformed

    private void jTnumeroFaturaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTnumeroFaturaFocusGained
      jTnumeroFatura.setText("");
      pack();
    }//GEN-LAST:event_jTnumeroFaturaFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int contador = listaLinhas.size();
        if(listaLinhas.isEmpty()){
             JOptionPane.showMessageDialog(this, "Ainda não foi inserida qualquer linha","Remoção de linhas", JOptionPane.WARNING_MESSAGE);
        } else
            listaLinhas.remove(contador -1);
        listaLinhas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jCtaxaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCtaxaActionPerformed
 
    }//GEN-LAST:event_jCtaxaActionPerformed

    
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBadicionarLinha;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCtaxa;
    private javax.swing.JComboBox jCtipoFatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLbaseTribLinhas;
    private javax.swing.JLabel jLivaLinhas;
    private javax.swing.JLabel jLtotalLinhas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTlinhas;
    private javax.swing.JTextField jTnifComerciante;
    private javax.swing.JTextField jTnifConsumidor;
    private javax.swing.JTextField jTnomeConsumidor;
    private javax.swing.JTextField jTnumeroFatura;
    private javax.swing.JTextField jTtotal;
    // End of variables declaration//GEN-END:variables
}
