/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import pg.EFactur;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nuno
 */
public class MenuAdmin extends javax.swing.JFrame {
    EFactur sistema;
    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin(EFactur sistema ) {
        this.sistema = sistema;
        initComponents();
        getContentPane().setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBnovoComerciante = new javax.swing.JButton();
        jBnovoConsumidor = new javax.swing.JButton();
        jBdivergencias = new javax.swing.JButton();
        jBlistaUtilizadores = new javax.swing.JButton();
        jBestatistica = new javax.swing.JButton();
        jBconsultaNif = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBlistaFaturas = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 255));
        setResizable(false);

        jBnovoComerciante.setBackground(new java.awt.Color(204, 204, 255));
        jBnovoComerciante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagens/add-user-icon.png"))); // NOI18N
        jBnovoComerciante.setText("Inserir Comerciante");
        jBnovoComerciante.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBnovoComerciante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovoComercianteActionPerformed(evt);
            }
        });

        jBnovoConsumidor.setBackground(new java.awt.Color(204, 204, 255));
        jBnovoConsumidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagens/add-user-icon.png"))); // NOI18N
        jBnovoConsumidor.setText("Inserir Consumidor");
        jBnovoConsumidor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBnovoConsumidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovoConsumidorActionPerformed(evt);
            }
        });

        jBdivergencias.setBackground(new java.awt.Color(204, 204, 255));
        jBdivergencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagens/divergencias.png"))); // NOI18N
        jBdivergencias.setText("Divergencias");
        jBdivergencias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBdivergencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdivergenciasActionPerformed(evt);
            }
        });

        jBlistaUtilizadores.setBackground(new java.awt.Color(204, 204, 255));
        jBlistaUtilizadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagens/users.png"))); // NOI18N
        jBlistaUtilizadores.setText("Listar Utilizadores");
        jBlistaUtilizadores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBlistaUtilizadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlistaUtilizadoresActionPerformed(evt);
            }
        });

        jBestatistica.setBackground(new java.awt.Color(204, 204, 255));
        jBestatistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagens/consultar.png"))); // NOI18N
        jBestatistica.setText("Estatistica");
        jBestatistica.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBestatistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBestatisticaActionPerformed(evt);
            }
        });

        jBconsultaNif.setBackground(new java.awt.Color(204, 204, 255));
        jBconsultaNif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagens/edituser.png"))); // NOI18N
        jBconsultaNif.setText("Editar Utilizador");
        jBconsultaNif.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBconsultaNif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconsultaNifActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrador");
        jLabel1.setToolTipText("");

        jBlistaFaturas.setBackground(new java.awt.Color(204, 204, 255));
        jBlistaFaturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagens/receipt.png"))); // NOI18N
        jBlistaFaturas.setText("Lista Faturas");
        jBlistaFaturas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBlistaFaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlistaFaturasActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setText("Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagens/lilsave.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(204, 204, 255));
        jButton8.setText("Sobre");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jBconsultaNif, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBnovoComerciante, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBlistaUtilizadores, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBestatistica, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jBdivergencias, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jBnovoConsumidor, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addGap(0, 121, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jBlistaFaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBdivergencias, jBestatistica, jBlistaUtilizadores, jBnovoComerciante, jBnovoConsumidor});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBnovoConsumidor, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBnovoComerciante, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBlistaUtilizadores, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jBdivergencias, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBconsultaNif, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jBestatistica, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
                .addGap(20, 20, 20)
                .addComponent(jBlistaFaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton8)
                .addGap(9, 9, 9))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBconsultaNif, jBdivergencias, jBestatistica, jBlistaUtilizadores, jBnovoComerciante, jBnovoConsumidor});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBnovoComercianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoComercianteActionPerformed
        ADnovoUtilizador nu = new ADnovoUtilizador("Comerciante", sistema);
        nu.setVisible(true);
        
    }//GEN-LAST:event_jBnovoComercianteActionPerformed

    private void jBnovoConsumidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoConsumidorActionPerformed
        ADnovoUtilizador nu = new ADnovoUtilizador("Consumidor", sistema);
        nu.setVisible(true);
    }//GEN-LAST:event_jBnovoConsumidorActionPerformed

    private void jBdivergenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdivergenciasActionPerformed
        ADoutput di = new ADoutput(sistema);
        di.setVisible(true);
    }//GEN-LAST:event_jBdivergenciasActionPerformed

    private void jBestatisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBestatisticaActionPerformed
       ADestatistica tf = new ADestatistica(sistema);
       tf.setVisible(true);
    }//GEN-LAST:event_jBestatisticaActionPerformed

    private void jBconsultaNifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultaNifActionPerformed
        ADnovoUtilizador consulta = new ADnovoUtilizador("Consulta", sistema);
        consulta.setVisible(true);
    }//GEN-LAST:event_jBconsultaNifActionPerformed

    private void jBlistaUtilizadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlistaUtilizadoresActionPerformed
        ADListaUtilizadores t = new ADListaUtilizadores(sistema);
        t.setVisible(true);
    }//GEN-LAST:event_jBlistaUtilizadoresActionPerformed

    private void jBlistaFaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlistaFaturasActionPerformed
       ADlistaFaturas lf = new ADlistaFaturas(sistema);
       lf.setVisible(true);
    }//GEN-LAST:event_jBlistaFaturasActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        sistema.gravar();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Sobre sob = new Sobre();
        sob.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        Login lg = new Login(sistema);
        dispose();
        lg.setVisible(true);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /** 
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBconsultaNif;
    private javax.swing.JButton jBdivergencias;
    private javax.swing.JButton jBestatistica;
    private javax.swing.JButton jBlistaFaturas;
    private javax.swing.JButton jBlistaUtilizadores;
    private javax.swing.JButton jBnovoComerciante;
    private javax.swing.JButton jBnovoConsumidor;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
